import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GlobalSpinner from "./components/Base/Spinner/GlobalSpinner";
import { SpinnerProvider } from "./context/SpinnerContext";



const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Soly Ticket",
  description: "Generated by DexterSol",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <SpinnerProvider>
       <GlobalSpinner />
      <body className={inter.className}>{children}</body>
      </SpinnerProvider>
    </html>
  );
}
